# Generated by Django 2.1.3 on 2019-10-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_Name', models.CharField(max_length=50)),
                ('faculty_ID', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('years_experience', models.CharField(max_length=50)),
            ],
        ),
    ]
